### ISSUE TITLE
Add rename warning to legacy `django-idom`

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy-django#142]
### Current Situation

`django-idom` has been renamed to `reactpy-django`. We need to warn existing users about this change.

### Proposed Actions

Add a print/log statement to `src/django_idom/__init__.py` to tell users about the rename.

We need to create a new branch based off of commit `b1ff783c887bbd7d93fdf586d21555692b502dcb` in order create new `django-idom` releases.

**Comment by Archmonger** [comment]
@rmorshea Can you review https://github.com/reactive-python/reactpy-django/commits/legacy-django-idom before I send out a release?

**Comment by rmorshea** [comment]
Is there a PR associated with that commit?

I'm away from my computer now, but I can create a `legacy-idom` branch that we can merge that into tomorrow. I can manually release that then.

**Comment by Archmonger** [comment]
I already created the branch, but did so without a PR.

**Comment by rmorshea** [comment]
LGTM.
